include junit error handling

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -41,7 +41,38 @@ jobs:
       - name: Assert failure
         if: success()
         run: |
-          echo "::error::failure-tests-notoken should have failed and reported annations on this step, but instead succeeded. But instead failed";
+          echo "::error::failure-tests-notoken should have failed and reported annations on this step. But instead succeeded";
+          exit 1;
+  error-tests:
+    runs-on: ubuntu-20.04
+    steps:
+      - uses: actions/checkout@v1
+      - name: Test action
+        uses: ./
+        with:
+          name: "error tests"
+          access-token: ${{ secrets.GITHUB_TOKEN }}
+          path: "**/TEST-Error.xml"
+          debug: true
+      - name: Assert success
+        if: failure()
+        run: |
+          echo "::error::error-tests should have succeeded, and created a new check that failed with annotations. But instead failed";
+          exit 1;
+  error-tests-notoken:
+    runs-on: ubuntu-20.04
+    steps:
+      - uses: actions/checkout@v1
+      - name: Test action
+        uses: ./
+        with:
+          name: "error tests no token"
+          path: "**/TEST-Error.xml"
+          debug: true
+      - name: Assert failure
+        if: success()
+        run: |
+          echo "::error::error-tests-notoken should have failed and reported annations on this step. But instead succeeded.";
           exit 1;
   success-tests:
     runs-on: ubuntu-20.04
